
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { currentUser } from '@clerk/nextjs/server'
import { Inter } from "next/font/google";
import 'react-loading-skeleton/dist/skeleton.css'

import "./globals.css";
import Provider from "@/lib/provider";
import { UpsertUser } from '@/service/userNew'
import { randomUUID } from "crypto";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const dataUser = await currentUser()

  if (dataUser) {
    await UpsertUser({
      "email": dataUser?.emailAddresses[0]?.emailAddress,
      "avatar": dataUser?.imageUrl,
      "IDCart": randomUUID(),
      "name": `${dataUser?.firstName} ${dataUser?.lastName} `,
      "clerkUserId": dataUser?.id
    })
  }

  return (
    <html lang="en">
      <Provider>
        <ClerkProvider afterSignOutUrl='/' >
          <body className={inter.className}>
            <NextTopLoader
              color="#2299DD"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              showSpinner={false}
              easing="ease"
              speed={200}
              shadow="0 0 10px #2299DD,0 0 5px #2299DD"
              template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
              zIndex={1600}
              showAtBottom={false}
            />
            {children}
          </body>
        </ClerkProvider>
      </Provider>
    </html >
  );
}
